<a href="https://colab.research.google.com/github/inefable12/UNMSM_quimica_2023/blob/main/Ejercicios_de_repaso_G8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1. Crea una lista de 10 números e imprime los valores negativos en otra lista

In [5]:
type([1,2,3,4])

list

In [20]:
mi_lista = [1,2,3,4,1,2,3,4,1,100]

In [21]:
2*mi_lista

[1, 2, 3, 4, 1, 2, 3, 4, 1, 100, 1, 2, 3, 4, 1, 2, 3, 4, 1, 100]

In [7]:
import numpy as np

In [15]:
mis_numeros = np.random.randint(1,20,size=10)

In [13]:
len(mis_numeros)

10

In [16]:
mis_numeros

array([13,  7, 15, 13, 12, 13,  6, 11, 13, 11])

In [17]:
2*mis_numeros

array([26, 14, 30, 26, 24, 26, 12, 22, 26, 22])

In [24]:
# [lo que quiero | como lo voy a generar]

[x*-1 for x in mi_lista]

[-1, -2, -3, -4, -1, -2, -3, -4, -1, -100]

# 2. Escribe una matriz de 3x3 con números float distintos

In [34]:
numeros = [[2.0,8.11,3.3],
           [3.4,2.55,9.1],
           [1.2,8.30,0.5]]

In [28]:
type([[2.0,8.11,3.3],[3,2,9],[1,8,0]])

list

In [35]:
numeros[2][1]

8.3

In [36]:
np.random.random_sample((3,3))

array([[0.4394605 , 0.80813932, 0.19129644],
       [0.49189843, 0.48940562, 0.58136422],
       [0.94484526, 0.90192317, 0.62521032]])

# 3. Crea una matriz A de 3x3 y 2 matrices (B y C) de 3x1 con números enteros distintos y calcula AxB+C

In [37]:
A = np.random.random_sample((3,3))
B = np.random.random_sample((3,1))
C = np.random.random_sample((3,1))

In [41]:
A.shape, B.shape, C.shape

((3, 3), (3, 1), (3, 1))

In [50]:
# La siguiente no es una operación entre matrices
A*B+C

array([[0.86878739, 1.01255075, 0.62261365],
       [1.03867444, 1.26893296, 1.34731037],
       [0.69991729, 0.81073851, 0.70418348]])

In [51]:
A@B+C

array([[2.22482553],
       [2.13261678],
       [2.10091143]])

In [52]:
np.dot(A,B)+C

array([[2.22482553],
       [2.13261678],
       [2.10091143]])

In [45]:
B

array([[0.85177757],
       [0.98457728],
       [0.84116951]])

In [46]:
C

array([[0.20025516],
       [0.68972772],
       [0.11954312]])

# 4. Disponer de números enteros desde el 1 hasta el 100 y cambiar los múltiplos de 3 por el string “m3”

In [ ]:
np.linspace(0,100,100)

In [58]:
mi_arreglo = np.arange(1,101)
mi_arreglo

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [59]:
len(mi_arreglo)

100

In [62]:
mi_arreglo%3

array([1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1,
       2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2,
       0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0,
       1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1,
       2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1])

In [63]:
mi_arreglo > 97

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False,  True,  True,
        True])

In [66]:
# llamar algún elemento
mi_arreglo[99]

100

In [70]:
if mi_arreglo[2]%3==0:
  print('sí, es múltiplo de 3')
else:
  print('no, no es múltiplo de 3')

sí, es múltiplo de 3


In [ ]:
for valor in mi_arreglo:
  if mi_arreglo[valor-1]%3==0:
    print(valor)
  else:
    print('adios')

In [73]:
# uso de "append"
lista_valores = []

for valor in mi_arreglo:
  if mi_arreglo[valor-1]%3==0:
    lista_valores.append(valor)

In [75]:
lista_valores = []

for valor in mi_arreglo:
  if mi_arreglo[valor-1]%3==0:
    lista_valores.append("m3")
  else:
    lista_valores.append(valor)

In [ ]:
lista_valores

In [ ]:
["m3" if i%3==0 else i for i in range(1,101)]

# 5. Recorriendo la matriz A del ejercicio 3, calcular la traza de la matriz transpuesta

In [79]:
A

array([[0.78486714, 0.95364755, 0.49585538],
       [0.35441273, 0.58827808, 0.66788323],
       [0.68996101, 0.82170761, 0.69503275]])

In [82]:
A[0][0] + A[1][1] + A[2][2]

2.068177975737729

In [88]:
# imprimir la diagonal
for indice,numero in enumerate(A):
  print(numero[indice])

0.7848671437147161
0.5882780825889086
0.6950327494341044


In [91]:
milista = []

for indice,numero in enumerate(A):
  milista.append(numero[indice])
  #print(numero[indice])

In [92]:
sum(milista)

2.068177975737729

# 6. Encuentra un autovalor y su autovector, para la matriz D. Puedes ayudarte multiplicando D con las matrices de 2x1 E, F y G

Si:

D = np.array([[3, 2], [1, 4]])

E = np.array([[1,0]])

F = np.array([[0,1]])

G = np.array([[1,1]])